---
title: "README"
author: "RLionheart"
date: "2/25/2021"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*THIS IS AN OLD, OUTDATED REPOSITORY THAT IS ACTING AS AN ARCHIVE. PLEASE GO TO PHOBOS, BELOW, FOR UPDATED INFORMATION.*
Most of this info can be found on the shared Google Drive under Collaborative Projects --> MARS and Phobos Project.

Within this repo, there are some example scripts from other lab members, archived code, original MARS projects functions, etc. 

[Phobos](https://github.com/IngallsLabUW/phobos)

---

## MARS
### Metabolite Annotation, Rank and Sort

The MARS project is a way to easily identify unknown mass features (MFs) in your data. It consists of three major sections: 

- A central database containing unknown mass features (MFs) with mz, rt and ms2 data detected by the Ingalls lab 
- A series of processes and functions for annotating, ranking, and scoring those MFs
- A central database containing annotated MFs from previous MARS missions

Flexible, updatable, searchable, rankable, exportable. 
